name: Gaming News Unlimited
favicon: null
layout_spectrum: 0.9378417497500777
typography_spectrum: 0.30376808857545257
title: Gaming News Unlimited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9915751868393272
  lightness: 0.9444406081456691
  saturation: 0.300439027370885
  rhythmicContrast: 0.018102534813806415
purpose: []
